packages:
  - packages/*
  - fluxer_admin
  - fluxer_api
  - fluxer_app
  - fluxer_app_proxy
  - fluxer_gateway
  - fluxer_integration
  - fluxer_marketing
  - fluxer_media_proxy

  - fluxer_relay_directory
  - fluxer_server
  - '!fluxer_docs'
  - '!fluxer_desktop'

allowBuilds:
  '@parcel/watcher': true
  argon2: true
  cpu-features: true
  core-js: true
  electron: true
  electron-winstaller: true
  esbuild: true
  msgpackr-extract: true
  msw: true
  onnxruntime-node: true
  protobufjs: true
  puppeteer: true
  sharp: true
  ssh2: true
  sqlite3: true
  uiohook-napi: true
  wasm-pack: true
blockExoticSubdeps: true
minimumReleaseAge: 1440
strictDepBuilds: true
trustPolicy: no-downgrade

catalog:
  '@atproto/api': 0.18.20
  '@aws-sdk/client-s3': 3.985.0
  '@aws-sdk/s3-request-presigner': 3.985.0
  '@biomejs/biome': 2.3.14
  '@bluesky-social/jwk-jose': 0.1.11
  '@bluesky-social/oauth-client-node': 0.3.9
  '@floating-ui/react': 0.27.17
  '@floating-ui/react-dom': 2.1.7
  '@hcaptcha/react-hcaptcha': 2.0.2
  '@hono/node-server': 1.19.9
  '@lingui/cli': 5.9.0
  '@lingui/core': 5.9.0
  '@lingui/react': 5.9.0
  '@lingui/swc-plugin': 5.10.1
  '@livekit/components-react': 2.9.19
  '@livekit/track-processors': 0.7.0
  '@marsidev/react-turnstile': 1.4.2
  '@messageformat/core': 3.4.0
  '@opentelemetry/api': 1.9.0
  '@opentelemetry/exporter-logs-otlp-http': 0.211.0
  '@opentelemetry/exporter-metrics-otlp-http': 0.211.0
  '@opentelemetry/exporter-trace-otlp-http': 0.211.0
  '@opentelemetry/instrumentation': 0.211.0
  '@opentelemetry/instrumentation-aws-sdk': 0.66.0
  '@opentelemetry/instrumentation-cassandra-driver': 0.56.0
  '@opentelemetry/instrumentation-fetch': 0.211.0
  '@opentelemetry/instrumentation-http': 0.211.0
  '@opentelemetry/instrumentation-pino': 0.57.0
  '@opentelemetry/resources': 2.5.0
  '@opentelemetry/sdk-logs': 0.211.0
  '@opentelemetry/sdk-metrics': 2.5.0
  '@opentelemetry/sdk-node': 0.211.0
  '@opentelemetry/sdk-trace-base': 2.5.0
  '@opentelemetry/semantic-conventions': 1.39.0
  '@phosphor-icons/react': 2.1.10
  '@radix-ui/react-checkbox': 1.3.3
  '@radix-ui/react-radio-group': 1.3.8
  '@radix-ui/react-switch': 1.2.6
  '@rspack/cli': 1.7.5
  '@rspack/core': 1.7.5
  '@sentry/node': 10.38.0
  '@sentry/react': 10.38.0
  '@simplewebauthn/browser': 13.2.2
  '@simplewebauthn/server': 13.2.2
  '@svgr/core': 8.1.0
  '@svgr/plugin-jsx': 8.1.0
  '@svgr/plugin-svgo': 8.1.0
  '@svgr/webpack': 8.1.0
  '@tailwindcss/cli': 4.1.18
  '@types/archiver': 7.0.0
  '@types/combokeys': 2.4.9
  '@types/jsdom': 27.0.0
  '@types/lodash': 4.17.23
  '@types/luxon': 3.7.1
  '@types/node': 25.2.2
  '@types/nodemailer': 7.0.9
  '@types/qrcode': 1.5.6
  '@types/react': 19.2.13
  '@types/react-dom': 19.2.3
  '@types/validator': 13.15.10
  '@types/ws': 8.18.1
  '@typescript/native-preview': 7.0.0-dev.20260209.1
  '@vitest/coverage-v8': 4.0.18
  ajv: 8.17.1
  archiver: 7.0.1
  argon2: 0.44.0
  autoprefixer: 10.4.24
  bowser: 2.14.1
  browserslist: 4.28.1
  cassandra-driver: 4.8.0
  chokidar: 5.0.0
  clsx: 2.1.1
  colorjs.io: 0.6.1
  combokeys: 3.0.1
  crc-32: 1.2.2
  cron-parser: 5.5.0
  css-select: 6.0.0
  domhandler: 5.0.3
  emoji-regex: 10.6.0
  esbuild: 0.27.3
  eventemitter3: 5.0.4
  fast-xml-parser: 5.3.5
  favico.js: 0.3.10
  framer-motion: 12.34.0
  fs-extra: 11.3.3
  happy-dom: 20.5.3
  hi-base32: 0.5.1
  highlight.js: 11.11.1
  hono: 4.11.9
  html-entities: 2.6.0
  htmlparser2: 10.1.0
  idna-uts46-hx: 6.1.0
  itty-time: 2.0.2
  ioredis: 5.8.1
  jose: 6.1.3
  jsdom: 28.0.0
  katex: 0.16.28
  knip: 5.83.1
  lightningcss: 1.31.1
  livekit-client: 2.17.1
  livekit-server-sdk: 2.15.0
  lodash: 4.17.23
  lru-cache: 11.2.5
  luxon: 3.7.2
  magic-bytes.js: 1.13.0
  match-sorter: 8.2.0
  maxmind: 5.0.5
  meilisearch: 0.55.0
  mime: 4.1.0
  mobx: 6.15.0
  mobx-persist-store: 1.1.8
  mobx-react-lite: 4.1.1
  motion: 12.34.0
  msgpackr: 1.11.8
  msw: 2.12.9
  nats: 2.29.3
  node-addon-api: 8.5.0
  nodemailer: 8.0.1
  onnxruntime-node: 1.24.1
  pino: 10.3.0
  pino-pretty: 13.1.3
  postcss: 8.5.6
  postcss-discard-comments: 7.0.5
  postcss-loader: 8.2.0
  postcss-modules: 6.0.1
  postcss-preset-env: 11.1.3
  qrcode: 1.5.4
  react: 19.2.4
  react-aria-components: 1.15.1
  react-day-picker: 9.13.1
  react-dnd: 16.0.1
  react-dnd-accessible-backend: 2.1.0
  react-dnd-html5-backend: 16.0.1
  react-dnd-multi-backend: 9.0.0
  react-dom: 19.2.4
  react-hook-form: 7.71.1
  react-hotkeys-hook: 5.2.4
  react-modal-sheet: 5.2.1
  react-select: 5.10.2
  react-zoom-pan-pinch: 3.7.0
  rxjs: 7.8.2
  sharp: 0.34.5
  stripe: 20.3.1
  tailwindcss: 4.1.18
  tempy: 3.2.0
  testcontainers: 11.11.0
  thumbhash: 0.1.1
  transliteration: 2.6.1
  ts-morph: 27.0.2
  tsx: 4.21.0
  typed-css-modules: 0.9.1
  uint8array-extras: 1.5.0
  unique-names-generator: 4.7.1
  urlpattern-polyfill: 10.1.0
  uuid: 13.0.0
  valibot: 1.2.0
  validator: 13.15.26
  vite-tsconfig-paths: 6.1.0
  vitest: 4.0.18
  wasm-pack: 0.14.0
  ws: 8.19.0
  yaml: 2.8.2
  zod: 4.3.6
