name: Bug report
description: Report a reproducible problem in Fluxer
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the report.

        Please check for existing issues before filing.
        Security issues should go to https://fluxer.app/security.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened, and what did you expect instead?
      placeholder: "When I ..., the app ..., but I expected ..."
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Provide clear, numbered steps.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See ...
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment (optional)
      description: Include versions that matter (commit/tag, OS, runtime, browser/device).
      placeholder: |
        - Commit/Tag:
        - OS:
        - Runtime:
        - Browser (if applicable):
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots (optional)
      description: Paste logs (redact secrets) or attach screenshots/recordings.
      placeholder: "Paste stack traces, console output, network errors, etc."
    validations:
      required: false
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I searched for existing issues and didn't find a duplicate.
          required: true
